name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip black 'jupyterlab>=4.0.0,<5'

      - name: Lint Python
        run: |
          black --check .

      - name: Lint JS
        run: |
          jlpm
          jlpm run lint:check
